### ISSUE TITLE
Error Sending Image

### ISSUE THREAD

**Issue by andyholiday** [california444/homebridge-doorbell-telegram-photo#112]
Hello,
first of all thanks for your work and the plugin.
I installed the plugin and the configuration was easy (i thought). 

But something left wrong and I always get the following message, when I touch the button to get the picture:

[02/05/2022, 15:28:36] [DoorbellPhotoTelegram Einfahrt] Doorbell ring...
[02/05/2022, 15:28:37] [DoorbellPhotoTelegram Einfahrt] Picture received successful!
[02/05/2022, 15:28:37] [DoorbellPhotoTelegram Einfahrt] Error while sending photo to Telegram!
[02/05/2022, 15:28:37] [DoorbellPhotoTelegram Einfahrt] ETELEGRAM: 404 Not Found

I think, that I configure the bot id or the Chat-Id not correctly. 

For the Bot-Id I tested everything: @Botname, Botname, Botnamebot
And the Chat ID I added including the "minus". 

Can you please help me? Is it correct, that I don't have to add the Bot-Token anywhere? 

Thanks in advance and best regards.

André

**Comment by california444** [comment]
Hi André,
Thanks for using the plugin. 
I‘m on vacation and have only limited internet access. 
The botId is a string which the “bot father” sent you during setting up the bot. 
Have you tried this one already?

Best Roman

**Comment by andyholiday** [comment]
Hi Roman,
ahhh now I get it. Thanks for your fast reply.
Have a nice vacation and best regards.
André

**Comment by california444** [comment]
Alright. Then I close this…
